<?php

namespace Winefing\ApiBundle\Repository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends \Doctrine\ORM\EntityRepository
{
    function findByUser($userId)
    {
        $query = $this->createQueryBuilder('address')
            ->join("address.articleCategory", "articleCategory")
            ->join("articleCategoryTr.language", "language")
            ->where('language.code = :langueCode and articleCategory.id = :articleCategory')
            ->setParameter('langueCode', 'fr')
            ->setParameter('articleCategory', $articleCategoryId)
            ->setMaxResults(1)
            ->getQuery();
        $frenchName = $query->getResult();
        var_dump($query->getResult());
        return $frenchName;
    }
}
