<?php

namespace Winefing\ApiBundle\Repository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends \Doctrine\ORM\EntityRepository
{
    function findAllByUser($userId)
    {
        $query = $this->createQueryBuilder('address')
            ->join("address.users", "user")
            ->where('user.id = :userId')
            ->setParameter('userId', $userId)
            ->getQuery();
        return $query->getResult();
    }
}
