<?php

namespace Winefing\ApiBundle\Repository;

/**
 * ArticleCategoryTrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleCategoryTrRepository extends \Doctrine\ORM\EntityRepository
{
}
