<?php

namespace Winefing\ApiBundle\Repository;

/**
 * ArticleTrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleTrRepository extends \Doctrine\ORM\EntityRepository
{
    function findOneByArticleIdLanguageId($articleId, $languageId) {
        $query = $this->createQueryBuilder('articleTr')
            ->join("articleTr.article", "article")
            ->join("articleTr.language", "language")
            ->where('language.id = :languageId and article.id = :articleId')
            ->setParameter('languageId', $languageId)
            ->setParameter('articleId', $articleId)
            ->setMaxResults(1)
            ->getQuery();
        $languages = $query->getResult();
        return $languages;
    }
}
