<?php

namespace Winefing\ApiBundle\Repository;
use Winefing\ApiBundle\Entity\Article;
use Doctrine\ORM\EntityRepository;


/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    function findByUserId($userId) {
        $query = $this->createQueryBuilder('article')
            ->join("article.user", "user")
            ->where('user.id = :userId')
            ->setParameter('userId', $userId)
            ->getQuery();
        $users = $query->getResult();
        return $users;
    }
}
