<?php

namespace Winefing\ApiBundle\Repository;
use Winefing\ApiBundle\Entity\Article;
use Doctrine\ORM\EntityRepository;


/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{

}
