<?php

namespace Winefing\ApiBundle\Repository;

/**
 * BoxItemTrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoxItemTrRepository extends \Doctrine\ORM\EntityRepository
{
}
