<?php

namespace Winefing\ApiBundle\Repository;

/**
 * BoxItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoxItemRepository extends \Doctrine\ORM\EntityRepository
{
}
