<?php

namespace Winefing\ApiBundle\Repository;

/**
 * BoxItemChoiceTrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoxItemChoiceTrRepository extends \Doctrine\ORM\EntityRepository
{
}
