<?php

namespace Winefing\ApiBundle\Repository;

/**
 * BoxItemChoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoxItemChoiceRepository extends \Doctrine\ORM\EntityRepository
{
}
