<?php

namespace Winefing\ApiBundle\Repository;

/**
 * BoxOrderItemChoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoxOrderItemChoiceRepository extends \Doctrine\ORM\EntityRepository
{
}
