<?php

namespace Winefing\ApiBundle\Repository;

/**
 * BoxTrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoxTrRepository extends \Doctrine\ORM\EntityRepository
{
}
