<?php

namespace Winefing\ApiBundle\Repository;

/**
 * CharacteristicRentalValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacteristicRentalValueRepository extends \Doctrine\ORM\EntityRepository
{

}
