<?php

namespace Winefing\ApiBundle\Repository;

/**
 * CharacteristicCategoryTrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacteristicCategoryTrRepository extends \Doctrine\ORM\EntityRepository
{
}
