<?php

namespace Winefing\ApiBundle\Repository;

/**
 * CharacteristicCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacteristicCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
