<?php

namespace Winefing\ApiBundle\Repository;

/**
 * CharacteristicPropertyValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacteristicPropertyValueRepository extends \Doctrine\ORM\EntityRepository
{

}
