<?php

namespace Winefing\ApiBundle\Repository;

/**
 * CharacteristicCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacteristicCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    function findDifferentFromId($id) {
        $query = $this->createQueryBuilder('c')
            ->where('c.id != :id')
            ->setParameter('id', array_values($id))
            ->getQuery();
        return $query->getResult();
    }
}
