<?php

namespace Winefing\ApiBundle\Repository;

/**
 * CharacteristicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacteristicRepository extends \Doctrine\ORM\EntityRepository
{
    function findMissingCharacteristics($ids, $scopeName) {
        if(empty($ids)) {
            $query = $this->createQueryBuilder('characteristic')
                ->join("characteristic.characteristicCategory", "characteristicCategory")
                ->join("characteristicCategory.scope", "scope")
                ->where('scope.name = :scopeName')
                ->setParameter('scopeName', $scopeName)
                ->getQuery();
            $characteristics = $query->getResult();
        } else {
            $query = $this->createQueryBuilder('characteristic')
                ->join("characteristic.characteristicCategory", "characteristicCategory")
                ->join("characteristicCategory.scope", "scope")
                ->where('characteristic.id not in (:ids) and scope.name = :scopeName')
                ->setParameter('ids', array_values($ids))
                ->setParameter('scopeName', $scopeName)
                ->getQuery();
            $characteristics = $query->getResult();
        }
        return $characteristics;
    }
}
