<?php

namespace Winefing\ApiBundle\Repository;

/**
 * CharacteristicValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacteristicValueRepository extends \Doctrine\ORM\EntityRepository
{

}
