<?php

namespace Winefing\ApiBundle\Repository;

/**
 * CharacteristicDomainValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacteristicDomainValueRepository extends \Doctrine\ORM\EntityRepository
{

}
