<?php

namespace Winefing\ApiBundle\Repository;

/**
 * CharacteristicTrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacteristicTrRepository extends \Doctrine\ORM\EntityRepository
{
}
