<?php

namespace Winefing\ApiBundle\Repository;

/**
 * DayPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DayPriceRepository extends \Doctrine\ORM\EntityRepository
{
}
