<?php

namespace Winefing\ApiBundle\Repository;

/**
 * EventRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
