<?php

namespace Winefing\ApiBundle\Repository;

/**
 * EventCategoryTrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventCategoryTrRepository extends \Doctrine\ORM\EntityRepository
{
}
