<?php

namespace Winefing\ApiBundle\Repository;

/**
 * IbanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IbanRepository extends \Doctrine\ORM\EntityRepository
{
}
