<?php

namespace Winefing\ApiBundle\Repository;
use Winefing\ApiBundle\Entity\Article;
use Winefing\ApiBundle\Entity\WebPage;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends \Doctrine\ORM\EntityRepository
{
    function findMissingLanguagesForArticle(Article $article) {
        foreach ($article->getArticleTrs() as $articleTr) {
            $languagesId[] = $articleTr->getLanguage()->getId();
        }
        $query = $this->createQueryBuilder('language')
            ->where('language.id not in (:languages)')
            ->setParameter('languages', array_values($languagesId))
            ->getQuery();
        $languages = $query->getResult();
        return $languages;
    }
    function findMissingLanguagesForWebPage(WebPage $webPage) {
        $webPagesId = array();
        foreach ($webPage->getWebPageTrs() as $webPageTr) {
            $webPagesId[] = $webPageTr->getLanguage()->getId();
        }
        $query = $this->createQueryBuilder('language')
            ->where('language.id not in (:languages)')
            ->setParameter('languages', array_values($webPagesId))
            ->getQuery();
        $languages = $query->getResult();
        return $languages;
    }
}
