<?php

namespace Winefing\ApiBundle\Repository;
/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends \Doctrine\ORM\EntityRepository
{
    function findMissingLanguages($id) {
        if(empty($id)) {
            $languages = $this->findAll();
        } else {
            $query = $this->createQueryBuilder('language')
                ->where('language.id not in (:languages)')
                ->setParameter('languages', array_values($id))
                ->getQuery();
            $languages = $query->getResult();
        }
        return $languages;
    }
}
