<?php

namespace Winefing\ApiBundle\Repository;
use Winefing\ApiBundle\Entity\ScopeEnum;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends \Doctrine\ORM\EntityRepository
{
}
