<?php

namespace Winefing\ApiBundle\Repository;

/**
 * PropertyCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
