<?php

namespace Winefing\ApiBundle\Repository;

/**
 * PropertyCategoryTrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyCategoryTrRepository extends \Doctrine\ORM\EntityRepository
{
}
