<?php

namespace Winefing\ApiBundle\Repository;

/**
 * RentalOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentalOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
