<?php

namespace Winefing\ApiBundle\Repository;

/**
 * RentalPromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentalPromotionRepository extends \Doctrine\ORM\EntityRepository
{
}
