<?php

namespace Winefing\ApiBundle\Repository;

/**
 * RentalOrderGiftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentalOrderGiftRepository extends \Doctrine\ORM\EntityRepository
{
}
