<?php

namespace Winefing\ApiBundle\Repository;

/**
 * SubscriptionTrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionTrRepository extends \Doctrine\ORM\EntityRepository
{
}
