<?php

namespace Winefing\ApiBundle\Repository;

/**
 * SubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUserGroup($userGroup) {
        $query = $this->createQueryBuilder('subscription')
            ->where('subscription.userGroup like :userGroup')
            ->setParameter('userGroup', '%'.$userGroup.'%')
            ->getQuery();
        return $query->getResult();
    }
}
