<?php

namespace Winefing\ApiBundle\Repository;

/**
 * TagTrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagTrRepository extends \Doctrine\ORM\EntityRepository
{
}
