<?php

namespace Winefing\ApiBundle\Repository;

/**
 * WebPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebPageRepository extends \Doctrine\ORM\EntityRepository
{
//    function findTitle($webPageId) {
//        $repository = $this->getDoctrine()->getRepository('WinefingApiBundle:WebPageTr');
//        $qb = $repository->createQueryBuilder('webPageTr');
//        $query = $qb
//            ->select('webPageTr.title')
//            ->join('webPageTr.webPage', 'webPage')
//            ->where('webPage.id = webPageId)')
//            ->setParameter('webPageId', $webPageId)
//            ->setMaxResults(1)
//            ->getQuery();
//        $webPageTr = $query->getResult();
//        var_dump($webPageTr);
//        return $webPageTr;
//    }
}
