<?php

namespace Winefing\ApiBundle\Repository;

/**
 * WineRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineRegionRepository extends \Doctrine\ORM\EntityRepository
{
    function findWithName($name) {
        $queryBuilder = $this->createQueryBuilder('wineRegion')
            ->join('wineRegion.wineRegionTrs', 'tr')
            ->where('tr.name like :name')
            ->setParameter('name', "%".$name."%")
            ->setMaxResults(1);
        $query = $queryBuilder->getQuery();
        return $query->getOneOrNullResult();
    }
}
