<?php

namespace Winefing\ApiBundle\Repository;

/**
 * WineRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineRegionRepository extends \Doctrine\ORM\EntityRepository
{

}
