<?php

namespace Winefing\ApiBundle\Repository;

/**
 * WineRegionTrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineRegionTrRepository extends \Doctrine\ORM\EntityRepository
{
}
