imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: doctrine_extensions.yml }
    - { resource: "@PaiementBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale:  fr
    host_comission: 10.00
    client_comission: 6.20
    tax: 20.00
    language_directory_upload: '%kernel.root_dir%/../web/Resources/pictures/language/'
    characteristic_category_directory_upload: '%kernel.root_dir%/../web/Resources/pictures/characteristicCategory/'
    characteristic_directory_upload: '%kernel.root_dir%/../web/Resources/pictures/characteristic/'
    article_directory_upload: '%kernel.root_dir%/../web/Resources/pictures/article/'
    domain_directory_upload: '%kernel.root_dir%/../web/Resources/pictures/domain/'
    user_directory_upload: '%kernel.root_dir%/../web/Resources/pictures/user/'
    property_directory_upload: '%kernel.root_dir%/../web/Resources/pictures/property/'
    rental_directory_upload: '%kernel.root_dir%/../web/Resources/pictures/rental/'
    box_directory_upload: '%kernel.root_dir%/../web/Resources/pictures/box/'

    language_directory: 'winefing/web/Resources/pictures/language/'
    credit_card_directory: '/winefing/web/Resources/credit-card/'
    characteristic_category_directory: 'winefing/web/Resources/pictures/characteristicCategory/'
    characteristic_directory: 'winefing/web/Resources/pictures/characteristic/'
    article_directory: 'winefing/web/Resources/pictures/article/'
    domain_directory: 'winefing/web/Resources/pictures/domain/'
    user_directory: 'winefing/web/Resources/pictures/user/'
    property_directory: 'winefing/web/Resources/pictures/property/'
    rental_directory: 'winefing/web/Resources/pictures/rental/'
    box_directory: 'winefing/web/Resources/pictures/box/'
    mail_chimp_token: '82eeea1796fe25cf7d185ec3ce2af340-us14'
    mail_chimp_url: 'https://us14.api.mailchimp.com/export/1.0/'

framework:
    #esi:             ~
    translator: { fallbacks: [%locale%] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer: true
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        host_comission: "%host_comission%"
        client_comission: "%client_comission%"
        language_directory: '%language_directory%'
        format_boolean: 'BOOLEAN'
        format_monnaie: 'MONNAIE'
        format_percentage: 'PERCENTAGE'
        format_text: 'TEXT'
        format_float: 'FLOAT'
        format_int: 'INT'
        format_time: 'TIME'
        format_date_time: 'DATETIME'
        format_date: 'DATE'
        format_varchar: 'VARCHAR'
        role_host : 'ROLE_HOST'
        role_admin : 'ROLE_ADMIN'
        role_user : 'ROLE_USER'
        address_billing : 'billing'
        address_delivering : 'delivering'
        user_directory : 'http://40.68.82.241/winefing/web/Resources/pictures/user/'


# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     localhost
        port:     ~
        dbname:   dev
        user:     root
        password: WhWo//2016
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
                translatable:
                    type: annotation
                    alias: Gedmo
                    prefix: Gedmo\Translatable\Entity
                    # make sure vendor library location is correct
                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                loggable:
                    type: annotation
                    alias: Gedmo
                    prefix: Gedmo\Loggable\Entity
                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                tree:
                    type: annotation
                    alias: Gedmo
                    prefix: Gedmo\Tree\Entity
                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#fos_rest:
#    view:
#        jsonp_handler: ~
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
    assets:
        bootstrap_css:
            inputs:
                - 'assets/vendor/bootstrap/dist/css/*'
        arillo_css:
            inputs:
                - 'bundles/app/css/*'

        bootstrap_js:
            inputs:
                - 'assets/vendor/bootstrap/dist/js/*'
        arillo_js:
            inputs:
                - 'bundles/app/js/*'
        jquery:
            inputs:
                - 'assets/vendor/jquery/dist/*'

nelmio_cors:
   defaults:
       allow_credentials: true
       allow_origin: []
       allow_headers: []
       allow_methods: []
       expose_headers: []
       max_age: 0
       hosts: []
   paths:
               '^/':
                   origin_regex: true
                   allow_origin: ['^http://104.47.146.137:[0-9]+']
                   allow_headers: ['X-Custom-Auth']
                   allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
                   max_age: 3600
                   hosts: ['^api\.']

jms_serializer:
    metadata:
        auto_detection: true

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json
