imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: doctrine_extensions.yml }
    - { resource: "@PaiementBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
            - { name: twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption: "%mail_encryption%"
    spool:     { type: memory }
framework:
    #esi:             ~
    translator: { fallbacks: [%locale%] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer: true
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        host_comission: "%host_comission%"
        client_comission: "%client_comission%"
        format_boolean: 'BOOLEAN'
        format_monnaie: 'MONNAIE'
        format_percentage: 'PERCENTAGE'
        format_text: 'TEXT'
        format_float: 'FLOAT'
        format_int: 'INT'
        format_time: 'TIME'
        format_date_time: 'DATETIME'
        format_date: 'DATE'
        format_varchar: 'VARCHAR'
        role_host : 'ROLE_HOST'
        role_admin : 'ROLE_ADMIN'
        role_user : 'ROLE_USER'
        address_billing : 'billing'
        address_delivering : 'delivering'
        let_your_self_directory : '%protocol%://%host_name%/%let_your_self_directory%/'
        discover_directory : '%protocol%://%host_name%/%discover_directory%/'
        picture_directory : '%protocol%://%host_name%/%picture_directory%/'
        language_directory: '%protocol%://%host_name%/%language_directory%/'
        credit_card_directory: '%protocol%://%host_name%/%credit_card_directory%/'
        characteristic_category_directory: '%protocol%://%host_name%/%characteristic_category_directory%/'
        characteristic_directory: '%protocol%://%host_name%/%characteristic_directory%/'
        article_directory: '%protocol%://%host_name%/%article_directory%/'
        domain_directory: '%protocol%://%host_name%/%domain_directory%/'
        user_directory: '%protocol%://%host_name%/%user_directory%/'
        wine_region_directory: '%protocol%://%host_name%/%wine_region_directory%/'
        property_directory: '%protocol%://%host_name%/%property_directory%/'
        rental_directory: '%protocol%://%host_name%/%rental_directory%'
        box_directory: '%protocol%://%host_name%/%box_directory%/'
        gift_card_directory: '%protocol%://%host_name%/%gift_card_directory%/'
        banner_directory: '%protocol%://%host_name%/%banner_directory%/'
        mail_chimp_token: '82eeea1796fe25cf7d185ec3ce2af340-us14'
        mail_chimp_url: 'https://us14.api.mailchimp.com/export/1.0/'
        rental_order_gift_price: '%rental_order_gift_price%'
        order_initiate: '%order_initiate%'
        order_validate: '%order_validate%'
        order_pay: '%order_pay%'
        order_cancel: '%order_cancel%'
        order_refused: '%order_refused%'
        tag_directory: '%protocol%://%host_name%/%tag_directory%/'
        winefing_facebook: '%winefing_facebook%'
        winefing_twitter: '%winefing_twitter%'
        winefing_instagram: '%winefing_instagram%'
        winefing_google: '%winefing_google%'
        winefing_email: '%winefing_email%'
        winefing_phone_number: '%winefing_phone_number%'
        winefing_street_address: '137'
        winefing_route: 'Rue Achard'
        winefing_postal_code: '33300'
        winefing_country: 'France'
        winefing_locality: 'Bordeaux'
        web_page_legal_notice: '%web_page_legal_notice%'
        web_page_gtu: '%web_page_gtu%'
        web_page_gts: '%web_page_gts%'
        web_page_faq: '%web_page_faq%'
        web_page_about: '%web_page_about%'
        gtu_route: '%gtu_route%'
        gts_route: '%gts_route%'
        invoice_host: '%invoice_host%'
        invoice_user: '%invoice_user%'
# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     localhost
        port:     ~
        dbname:   dev
        user:     root
        password: WhWo//2016audrey
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
                translatable:
                    type: annotation
                    alias: Gedmo
                    prefix: Gedmo\Translatable\Entity
                    # make sure vendor library location is correct
                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                loggable:
                    type: annotation
                    alias: Gedmo
                    prefix: Gedmo\Loggable\Entity
                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                tree:
                    type: annotation
                    alias: Gedmo
                    prefix: Gedmo\Tree\Entity
                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"



#fos_rest:
#    view:
#        jsonp_handler: ~
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
    assets:
        font_awesome_css:
            inputs:
            - 'assets/vendor/font-awesome-4.7.0.2/css/font-awesome.min.css'
        clockpicker_css:
            inputs:
                - 'assets/vendor/clockpicker/dist/bootstrap-clockpicker.min.css'
        phone_number_css:
            inputs:
                - 'assets/vendor/intl-tel-input/build/css/intlTelInput.css'
        bootstrap_select_css:
            inputs:
                - 'assets/vendor/bootstrap_select/dist/css/bootstrap-select.min.css'
        bootstrap_slider_range_css:
            inputs:
                - 'assets/vendor/seiyria-bootstrap-slider/dist/css/bootstrap-slider.min.css'
        bootflat_css:
            inputs:
                - 'assets/vendor/Bootflat/bootflat/css/bootflat.min.css'
        toast_css:
            inputs:
                - 'assets/vendor/jquery-toast-plugin/dist/jquery.toast.min.css'
        phone_number_js:
            inputs:
                - 'assets/vendor/intl-tel-input/build/js/intlTelInput.js'
        bootstrap_css:
            inputs:
                - 'assets/vendor/bootstrap/dist/css/*'
        arillo_css:
            inputs:
                - 'bundles/app/css/arillo/*'
        unify_css:
            inputs:
                - 'bundles/app/css/unify/*'
        custom_css:
            inputs:
                - 'bundles/app/css/custom/*'
        other_css:
            inputs:
                - 'bundles/app/css/other/*'
        bootstrap_js:
            inputs:
                - 'assets/vendor/bootstrap/dist/js/*'
        arillo_js:
            inputs:
                - 'bundles/app/js/*'
        jquery:
            inputs:
                - 'assets/vendor/jquery/dist/*'

nelmio_cors:
   defaults:
       allow_credentials: true
       allow_origin: []
       allow_headers: []
       allow_methods: []
       expose_headers: []
       max_age: 0
       hosts: []
   paths:
               '^/':
                   origin_regex: true
                   allow_origin: ['^http://104.47.146.137:[0-9]+']
                   allow_headers: ['X-Custom-Auth']
                   allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
                   max_age: 3600
                   hosts: ['^api\.']

jms_serializer:
    metadata:
        auto_detection: true

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json

nelmio_api_doc:
    sandbox:
        accept_type:        "application/json"
        body_format:
            formats:        [ "json" ]
            default_format: "json"
        request_format:
            formats:
                json:       "application/json"

fos_oauth_server:
    db_driver:           orm
    client_class:        Winefing\ApiBundle\Entity\Client
    access_token_class:  Winefing\ApiBundle\Entity\AccessToken
    refresh_token_class: Winefing\ApiBundle\Entity\RefreshToken
    auth_code_class:     Winefing\ApiBundle\Entity\AuthCode
    service:
      user_provider: winefing.api.user_provider
      options:
          supported_scopes: user
          access_token_lifetime: 3600
knp_snappy:
    temporary_folder: %kernel.cache_dir%/snappy

knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/bin/wkhtmltopdf #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\"" for Windows users
        options:    []
#    image:
#        enabled:    true
#        binary:     http://azure.archive.ubuntu.com/ubuntu #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\"" for Windows users
#        options:    []