imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: doctrine_extensions.yml }
    - { resource: "@PaiementBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption: "%mail_encryption%"
    spool:     { type: memory }
framework:
    #esi:             ~
    translator: { fallbacks: [%locale%] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer: true
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        host_comission: "%host_comission%"
        client_comission: "%client_comission%"
        format_boolean: 'BOOLEAN'
        format_monnaie: 'MONNAIE'
        format_percentage: 'PERCENTAGE'
        format_text: 'TEXT'
        format_float: 'FLOAT'
        format_int: 'INT'
        format_time: 'TIME'
        format_date_time: 'DATETIME'
        format_date: 'DATE'
        format_varchar: 'VARCHAR'
        role_host : 'ROLE_HOST'
        role_admin : 'ROLE_ADMIN'
        role_user : 'ROLE_USER'
        address_billing : 'billing'
        address_delivering : 'delivering'
        let_your_self_directory : '%protocol%://%host_name%/%let_your_self_directory%/'
        discover_directory : '%protocol%://%host_name%/%discover_directory%/'
        picture_directory : '%protocol%://%host_name%/%picture_directory%/'
        language_directory: '%protocol%://%host_name%/%language_directory%/'
        credit_card_directory: '%protocol%://%host_name%/%credit_card_directory%/'
        characteristic_category_directory: '%protocol%://%host_name%/%characteristic_category_directory%/'
        characteristic_directory: '%protocol%://%host_name%/winefing/%characteristic_directory%/'
        article_directory: '%protocol%://%host_name%/%article_directory%/'
        domain_directory: '%protocol%://%host_name%/%domain_directory%/'
        user_directory: '%protocol%://%host_name%/%user_directory%/'
        property_directory: '%protocol%://%host_name%/%property_directory%/'
        rental_directory: '%protocol%://%host_name%/%rental_directory%/'
        box_directory: '%protocol%://%host_name%/%box_directory%/'
        mail_chimp_token: '82eeea1796fe25cf7d185ec3ce2af340-us14'
        mail_chimp_url: 'https://us14.api.mailchimp.com/export/1.0/'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     localhost
        port:     ~
        dbname:   dev
        user:     root
        password: WhWo//2016audrey
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
                translatable:
                    type: annotation
                    alias: Gedmo
                    prefix: Gedmo\Translatable\Entity
                    # make sure vendor library location is correct
                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                loggable:
                    type: annotation
                    alias: Gedmo
                    prefix: Gedmo\Loggable\Entity
                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                tree:
                    type: annotation
                    alias: Gedmo
                    prefix: Gedmo\Tree\Entity
                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"



#fos_rest:
#    view:
#        jsonp_handler: ~
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
    assets:
        phone_number_css:
            inputs:
                - 'assets/vendor/intl-tel-input/build/css/intlTelInput.css'
        phone_number_js:
            inputs:
                - 'assets/vendor/intl-tel-input/build/js/intlTelInput.js'
        bootstrap_css:
            inputs:
                - 'assets/vendor/bootstrap/dist/css/*'
        arillo_css:
            inputs:
                - 'bundles/app/css/arillo/*'
        unify_css:
            inputs:
                - 'bundles/app/css/unify/*'
        custom_css:
            inputs:
                - 'bundles/app/css/custom/*'
        other_css:
            inputs:
                - 'bundles/app/css/other/*'
        bootstrap_js:
            inputs:
                - 'assets/vendor/bootstrap/dist/js/*'
        arillo_js:
            inputs:
                - 'bundles/app/js/*'
        jquery:
            inputs:
                - 'assets/vendor/jquery/dist/*'

nelmio_cors:
   defaults:
       allow_credentials: true
       allow_origin: []
       allow_headers: []
       allow_methods: []
       expose_headers: []
       max_age: 0
       hosts: []
   paths:
               '^/':
                   origin_regex: true
                   allow_origin: ['^http://104.47.146.137:[0-9]+']
                   allow_headers: ['X-Custom-Auth']
                   allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
                   max_age: 3600
                   hosts: ['^api\.']

jms_serializer:
    metadata:
        auto_detection: true

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json

nelmio_api_doc:
    sandbox:
        accept_type:        "application/json"
        body_format:
            formats:        [ "json" ]
            default_format: "json"
        request_format:
            formats:
                json:       "application/json"

fos_oauth_server:
    db_driver:           orm
    client_class:        Winefing\ApiBundle\Entity\Client
    access_token_class:  Winefing\ApiBundle\Entity\AccessToken
    refresh_token_class: Winefing\ApiBundle\Entity\RefreshToken
    auth_code_class:     Winefing\ApiBundle\Entity\AuthCode
    service:
      user_provider: winefing.api.user_provider
      options:
          supported_scopes: user
          access_token_lifetime: 3600
