user:
    resource: "@WinefingUserBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}

paiement:
    resource: "@PaiementBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

winefing_api:
    type: rest
    prefix: /{_locale}/api
    resource: "@WinefingApiBundle/Resources/config/routing.yml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: en|fr

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

logout:
    path: /logout