# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        our_db_provider:
            entity:
                class: WinefingApiBundle:User
                property: email
        myProvider:
            id: winefing.api.user_provider
    encoders:
        Winefing\ApiBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_TECHNIQUE
        ROLE_ADMIN: [ROLE_MANAGER, ROLE_TECHNIQUE]
        ROLE_BLOG: [ROLE_MANAGER, ROLE_TECHNIQUE, ROLE_BLOG]
        ROLE_HOST: ROLE_HOST
        ROLE_USER: ROLE_USER

    firewalls:
#        oauth_token:                                   # Everyone can access the access token URL.
#            pattern: ^/oauth/v2/token
#            security: false
##        oauth_authorize:
##            pattern:    ^/oauth/v2/auth
#        api:
#            pattern: ^/api                                # All URLs are protected
#            fos_oauth: true                            # OAuth2 protected resource
#            stateless: true                            # Do no set session cookies
#            anonymous: false
#        api:
#            pattern: ^/api/
#            anonymous: true
#            guard:
#                authenticators:
#                    - app.api_token_authenticator
        main:
            pattern:  ^/
            anonymous: true
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            provider: our_db_provider
            form_login:
              login_path: login
              check_path: login
              success_handler: winefing.component.authentication.handler.login_success_handler
              csrf_parameter: _csrf_security_token
              csrf_token_id: a_private_string
              default_target_path: home
              always_use_default_target_path: true
            logout:
                path:   /logout
                target: home

#                # by default, use the start() function from FormLoginAuthenticator
#                entry_point: app.form_login_authenticator

    access_control:
#        - { path: ^/%locale%/registration, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/%locale%/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/%locale%/logout, role: IS_AUTHENTICATED_FULLY }
#        - { path: ^/%locale%/logout, role: IS_AUTHENTICATED_FULLY }
#        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
##        - { path: ^/%locale%/admin/, role: ROLE_ADMIN }
##        - { path: ^/%locale%/host/, role: ROLE_HOST }
#        - { path: ^/%locale%/paiement/, role: IS_AUTHENTICATED_FULLY }
#        - { path: ^/api/doc, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/api, role: IS_AUTHENTICATED_ANONYMOUSLY }
