# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        our_db_provider:
            entity:
                class: WinefingApiBundle:User
                property: email
    encoders:
        Winefing\ApiBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_TECHNIQUE
        ROLE_ADMIN: [ROLE_MANAGER, ROLE_TECHNIQUE]
        ROLE_BLOG: [ROLE_MANAGER, ROLE_TECHNIQUE, ROLE_BLOG]
        ROLE_HOST: ROLE_HOST
        ROLE_USER: ROLE_USER



    firewalls:
        main:
            pattern:  ^/
            anonymous: true
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            provider: our_db_provider
            form_login:
              login_path: login
              check_path: login
              success_handler: winefing.component.authentication.handler.login_success_handler
              csrf_parameter: _csrf_security_token
              csrf_token_id: a_private_string
              default_target_path: home
              always_use_default_target_path: true
            logout:
                path:   /logout
                target: home

    access_control:
        - { path: ^/%locale%/registration, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%locale%/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%locale%/logout, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/%locale%/logout, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%locale%/admin/, role: ROLE_ADMIN }
        - { path: ^/%locale%/host/, role: ROLE_HOST }
        - { path: ^/%locale%/paiement/, role: IS_AUTHENTICATED_FULLY }
