# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    winefing.api_controller:
        class: Winefing\ApiBundle\Controller\ApiController
    winefing.serializer_controller:
            class: Winefing\ApiBundle\Controller\SerializerController
    winefing.webpath_controller:
            class: Winefing\ApiBundle\Controller\WebPathController
    winefing.media_format_controller:
        class: Winefing\ApiBundle\Controller\MediaFormatController
    winefing.media_format_controller:
        class: Winefing\ApiBundle\Controller\MediaFormatController
    winefing.missing_characteristic_controller:
        class: Winefing\ApiBundle\Controller\MissingCharacteristicController
    winefing.lemonway_controller:
        class: PaiementBundle\Controller\LemonWayController
        arguments: ["@fos_user.user_manager" ]