# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    winefing.login_success_handler.class: Winefing\UserBundle\Controller\LoginSuccessHandler

services:
    winefing.api_controller:
        class: Winefing\ApiBundle\Controller\ApiController
        arguments: ['@service_container', "@=service('security.token_storage').getToken()", '@winefing.repository.refresh_token']
    winefing.geocoder_controller:
        class: Winefing\ApiBundle\Controller\GeocodeAddressController
    winefing.characteristic_service:
        class: AppBundle\Controller\CharacteristicService
        arguments: ['@winefing.api_controller', "@router", '@jms_serializer']
    winefing.serializer_controller:
            class: Winefing\ApiBundle\Controller\SerializerController
    winefing.webpath_controller:
            class: Winefing\ApiBundle\Controller\WebPathController
    winefing.media_format_controller:
        class: Winefing\ApiBundle\Controller\MediaFormatController
    winefing.media_format_controller:
        class: Winefing\ApiBundle\Controller\MediaFormatController
    winefing.missing_characteristic_controller:
        class: Winefing\ApiBundle\Controller\MissingCharacteristicController
    winefing.lemonway_controller:
        class: PaiementBundle\Controller\LemonWayController
        arguments: ["@doctrine.orm.entity_manager", "@jms_serializer" ]
    winefing.component.authentication.handler.login_success_handler:
        class:  %winefing.login_success_handler.class%
        arguments:  ["@router", "@winefing.api_controller", "@winefing.webpath_controller", '@service_container']
    app.api_token_authenticator:
        class: Winefing\ApiBundle\Controller\TokenAuthenticator
        arguments: ["@doctrine.orm.entity_manager"]
    winefing.api.user_provider:
            class: Winefing\ApiBundle\Controller\ApiUserProvider
            arguments: ['@doctrine.orm.entity_manager']
    winefing.repository.refresh_token:
        class: Winefing\ApiBundle\Repository\RefreshTokenRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Winefing\ApiBundle\Entity\RefreshToken