language:
    type: rest
    resource: Winefing\ApiBundle\Controller\LanguageController
    name_prefix:  api_

format:
    type: rest
    resource: Winefing\ApiBundle\Controller\FormatController
    name_prefix:  api_

characteristicCategory:
    type: rest
    resource: Winefing\ApiBundle\Controller\CharacteristicCategoryController
    name_prefix:  api_

characteristicCategoryTr:
    type: rest
    resource: Winefing\ApiBundle\Controller\CharacteristicCategoryTrController
    name_prefix:  api_

characteristic:
    type: rest
    resource: Winefing\ApiBundle\Controller\CharacteristicController
    name_prefix:  api_

characteristicTr:
    type: rest
    resource: Winefing\ApiBundle\Controller\CharacteristicTrController
    name_prefix:  api_

article:
    type: rest
    resource: Winefing\ApiBundle\Controller\ArticleController
    name_prefix:  api_

articleCategory:
    type: rest
    resource: Winefing\ApiBundle\Controller\ArticleCategoryController
    name_prefix:  api_

articleCategoryTr:
    type: rest
    resource: Winefing\ApiBundle\Controller\ArticleCategoryTrController
    name_prefix:  api_

articleTr:
    type: rest
    resource: Winefing\ApiBundle\Controller\ArticleTrController
    name_prefix:  api_

promotion:
    type: rest
    resource: Winefing\ApiBundle\Controller\PromotionController
    name_prefix:  api_

webPage:
    type: rest
    resource: Winefing\ApiBundle\Controller\WebPageController
    name_prefix:  api_

webPageTr:
    type: rest
    resource: Winefing\ApiBundle\Controller\WebPageTrController
    name_prefix:  api_

country:
    type: rest
    resource: Winefing\ApiBundle\Controller\CountryController
    name_prefix:  api_

wineRegion:
    type: rest
    resource: Winefing\ApiBundle\Controller\WineRegionController
    name_prefix:  api_

wineRegionTr:
    type: rest
    resource: Winefing\ApiBundle\Controller\WineRegionTrController
    name_prefix:  api_

tag:
    type: rest
    resource: Winefing\ApiBundle\Controller\TagController
    name_prefix:  api_

tagTr:
    type: rest
    resource: Winefing\ApiBundle\Controller\TagTrController
    name_prefix:  api_

subscription:
    type: rest
    resource: Winefing\ApiBundle\Controller\SubscriptionController
    name_prefix:  api_

subscriptionTr:
    type: rest
    resource: Winefing\ApiBundle\Controller\SubscriptionTrController
    name_prefix:  api_

address:
    type: rest
    resource: Winefing\ApiBundle\Controller\AddressController
    name_prefix:  api_

domain:
    type: rest
    resource: Winefing\ApiBundle\Controller\DomainController
    name_prefix:  api_

user:
    type: rest
    resource: Winefing\ApiBundle\Controller\UserController
    name_prefix:  api_

characteristicDomainValue:
    type: rest
    resource: Winefing\ApiBundle\Controller\CharacteristicDomainValueController
    name_prefix:  api_
characteristicValue:
    type: rest
    resource: Winefing\ApiBundle\Controller\CharacteristicValueController
    name_prefix:  api_
rental:
    type: rest
    resource: Winefing\ApiBundle\Controller\RentalController
    name_prefix:  api_
property:
    type: rest
    resource: Winefing\ApiBundle\Controller\PropertyController
    name_prefix:  api_
media:
    type: rest
    resource: Winefing\ApiBundle\Controller\MediaController
    name_prefix:  api_

eventRequest:
    type: rest
    resource: Winefing\ApiBundle\Controller\EventRequestController
    name_prefix:  api_

rentalPromotions:
    type: rest
    resource: Winefing\ApiBundle\Controller\RentalPromotionController
    name_prefix:  api_

box:
    type: rest
    resource: Winefing\ApiBundle\Controller\BoxController
    name_prefix:  api_

boxTr:
    type: rest
    resource: Winefing\ApiBundle\Controller\BoxTrController
    name_prefix:  api_

boxItem:
    type: rest
    resource: Winefing\ApiBundle\Controller\BoxItemController
    name_prefix:  api_

boxItemTr:
    type: rest
    resource: Winefing\ApiBundle\Controller\BoxItemTrController
    name_prefix:  api_

boxItemChoice:
    type: rest
    resource: Winefing\ApiBundle\Controller\BoxItemChoiceController
    name_prefix:  api_

boxItemChoiceTr:
    type: rest
    resource: Winefing\ApiBundle\Controller\BoxItemChoiceTrController
    name_prefix:  api_

propertyCategory:
    type: rest
    resource: Winefing\ApiBundle\Controller\PropertyCategoryController
    name_prefix:  api_

propertyCategoryTr:
    type: rest
    resource: Winefing\ApiBundle\Controller\PropertyCategoryTrController
    name_prefix:  api_

creditCard:
    type: rest
    resource: Winefing\ApiBundle\Controller\CreditCardController
    name_prefix:  api_

dayPrice:
    type: rest
    resource: Winefing\ApiBundle\Controller\CreditCardController
    name_prefix:  api_

rentalOrder:
    type: rest
    resource: Winefing\ApiBundle\Controller\RentalOrderController
    name_prefix:  api_

email:
    type: rest
    resource: Winefing\ApiBundle\Controller\EmailController
    name_prefix:  api_