language:
    type: rest
    resource: Winefing\ApiBundle\Controller\LanguageController
    name_prefix:  api_

format:
    type: rest
    resource: Winefing\ApiBundle\Controller\FormatController
    name_prefix:  api_

characteristicCategory:
    type: rest
    resource: Winefing\ApiBundle\Controller\CharacteristicCategoryController
    name_prefix:  api_

characteristicCategoryTr:
    type: rest
    resource: Winefing\ApiBundle\Controller\CharacteristicCategoryTrController
    name_prefix:  api_

characteristic:
    type: rest
    resource: Winefing\ApiBundle\Controller\CharacteristicController
    name_prefix:  api_

characteristicTr:
    type: rest
    resource: Winefing\ApiBundle\Controller\CharacteristicTrController
    name_prefix:  api_

article:
    type: rest
    resource: Winefing\ApiBundle\Controller\ArticleController
    name_prefix:  api_

articleCategory:
    type: rest
    resource: Winefing\ApiBundle\Controller\ArticleCategoryController
    name_prefix:  api_

articleTr:
    type: rest
    resource: Winefing\ApiBundle\Controller\ArticleTrController
    name_prefix:  api_

promotion:
    type: rest
    resource: Winefing\ApiBundle\Controller\PromotionController
    name_prefix:  api_

adminUser:
    type: rest
    resource: Winefing\ApiBundle\Controller\AdminUserController
    name_prefix:  api_

webPage:
    type: rest
    resource: Winefing\ApiBundle\Controller\WebPageController
    name_prefix:  api_

webPageTr:
    type: rest
    resource: Winefing\ApiBundle\Controller\WebPageTrController
    name_prefix:  api_